apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-app
  namespace: argocdd
spec:
  project: default
  source: 
    repoURL: https://github.com/otmallah/argoCD.git
    targetRevision: HEAD
    path: hello
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true    
